production:
  adapter: mysql2
  encoding: utf8
  database: cf_production
  pool: 20
  host: 10.183.248.28
  username: james
  password: <%= ENV['DB_PASSWORD'] %>
  reconnect: true

staging:
  adapter: mysql2
  encoding: utf8
  database: cf_production
  pool: 20
  host: 10.183.248.28
  username: james
  password: <%= ENV['DB_PASSWORD'] %>
  reconnect: true

test: &TEST
  adapter: mysql2
  encoding: utf8
  database: cf_test
  pool: 20
  username: root
  password: F4flkgj43LWB#$LW#E$GFsrdknmfgn#$
  reconnect: true

development:
  adapter: mysql2
  encoding: utf8
  database: cf_development
  pool: 20
  username: root
  password: F4flkgj43LWB#$LW#E$GFsrdknmfgn#$
  reconnect: true
