production:
  adapter: mysql2
  encoding: utf8
  database: cf_production
  pool: 5
  host: bb01e06aa298a9c72d3027604ca50021a0c2d79e.rackspaceclouddb.com
  username: james
  password: F4flkgj43LWB#$LW#E$GFsrdknmfgn#$

test: &TEST
  adapter: mysql2
  encoding: utf8
  database: cf_test
  pool: 5
  username: root
  password: F4flkgj43LWB#$LW#E$GFsrdknmfgn#$

development:
  adapter: mysql2
  encoding: utf8
  database: cf_development
  pool: 5
  username: root
  password: F4flkgj43LWB#$LW#E$GFsrdknmfgn#$
