development:
  adapter: postgresql
  encoding: utf8
  database: cf_development
  pool: 5
  username: james
  password: F4flkgj43LWB#$LW#E$GFsrdknmfgn#$

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: cf_test
  pool: 5
  username: james
  password: F4flkgj43LWB#$LW#E$GFsrdknmfgn#$

production:
  adapter: postgresql
  encoding: utf8
  database: cf_production
  pool: 5
  username: james
  password: F4flkgj43LWB#$LW#E$GFsrdknmfgn#$
